In [7]:
import pandas as pd
print("libraries are imported ")

libraries are imported

In [8]:
df=pd.read_csv('student_performance.csv')
print("dataset loaded successfully")

dataset loaded successfully

In [9]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [10]:
print("shape of dataset:",df.shape)
print("number of rows:",df.shape[0])
print("number of columns:",df.shape[1])

shape of dataset: (30, 13)
number of rows: 30
number of columns: 13

In [11]:
print("column in datasets:")
print(df.columns.tolist())

column in datasets:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [12]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [13]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [14]:
print("missiing values in each cloumn:")
print(df.isnull().sum())

missiing values in each cloumn:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [15]:
print("student names:")
print(df['name'])

student names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [16]:
print("department in this dataset:")
print(df['department'].unique())

department in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [17]:
print("how many students per department:")
print(df['department'].value_counts())

how many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [18]:
cs_students=df[df['department']=='Computer Science']
print(f"Number of computer science students:{len(cs_students)}")
print(cs_students[['name','math_score','programming_score','attendance_percentage']])

Number of computer science students:13
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [19]:
high_attendance =df[df['attendance_percentage']>90]
print(f"Number of students with high attendance:{len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Number of students with high attendance:10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [20]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98

In [21]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("average total score for each department:")
print(dept_avg)

average total score for each department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [22]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print("top 10 students by score:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

top 10 students by score:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

MINI PROJECT
objective
create a student performance Explorer using python and pandas
to analyze student data and generate the detailed report
Dataset columns:
name
gender
department
math_score
programming_score
attendance_percentage
total_score
Tasks to Perform:

1, Display Project Title
Print a formatted title with separator lines.
2. Dataset Overview
Display:
- Total number of students
- Total number of columns
- Number of unique departments
3. Department-wise Analysis
Display the count of students in each department.
4. Score Analysis
Find and display:
- Highest math score
* Lowest math score
- Average math score
- Averuge programming score
- Average attendance percentage
5. Gender-wise Analysis
Calculate and display average total score grouped by gender.
6. Top Performers
Display the top 5 students based on total_score.
Show:
- Student Name
- Department
- Total Score
7. Attendance Analysis
Find students whose attendance is below 75%.
Display:
- Name
- Department
- Attendance Percentage
If all students have attendance above 75%, print a suitable message.
Concepts to Use:
-pandas, DataFrame, groupby, value_counts(), mean(), max(), min, sort_values, iterrows(), Conditional statements, f-strings

In [27]:


print("=" * 65)
print("        STUDENT PERFORMANCE EXPLORER USING PANDAS")
print("=" * 65)



print("Datas are loaded")

# Create total_score column
df["total_score"] = df["math_score"] + df["programming_score"]

# -------------------------------------------------
# First 5 Records
# -------------------------------------------------
print("-" * 65)
print("\nFIRST 5 RECORDS")
print("-" * 65)

print(df.head())

# -------------------------------------------------
# Dataset Overview
# -------------------------------------------------
print("-" * 65)
print("\nDATASET OVERVIEW")
print("-" * 65)

total_students = df.shape[0]
total_columns = df.shape[1]

print(f"Total Number of Students : {total_students}")
print(f"Total Number of Columns  : {total_columns}")

# -------------------------------------------------
# Department-wise Analysis
# -------------------------------------------------
print("-" * 65)
print("\nDEPARTMENT-WISE ANALYSIS")
print("-" * 65)

department_count = df["department"].value_counts()

print(department_count)

# -------------------------------------------------
# Score Analysis
# -------------------------------------------------


print("-" * 65)
print("\nSCORE ANALYSIS")
print("-" * 65)

highest_math_score = df["math_score"].max()
lowest_math_score = df["math_score"].min()

average_math_score = df["math_score"].mean()
average_programming_score = df["programming_score"].mean()
average_attendance = df["attendance_percentage"].mean()

print(f"Highest Math Score              : {highest_math_score}")
print(f"Lowest Math Score               : {lowest_math_score}")
print(f"Average Math Score              : {average_math_score:.2f}")
print(f"Average Programming Score       : {average_programming_score:.2f}")
print(f"Average Attendance Percentage   : {average_attendance:.2f}%")


# -------------------------------------------------
# Gender-wise Analysis
# -------------------------------------------------
print("-" * 65)
print("\nGENDER-WISE ANALYSIS")
print("-" * 65)

gender_average = df.groupby("gender")["total_score"].mean()

for gender, average_score in gender_average.items():
    print(f"{gender} Average Total Score : {average_score:.2f}")

# -------------------------------------------------
# Top 5 Performers
# -------------------------------------------------
print("-" * 65)
print("\nTOP 5 PERFORMERS")
print("-" * 65)

top_students = df.sort_values(by="total_score", ascending=False).head(5)

for index, row in top_students.iterrows():

    print(f"Student Name : {row['name']}")
    print(f"Department   : {row['department']}")
    print(f"Total Score  : {row['total_score']}")
    print("-" * 40)

# -------------------------------------------------
# Attendance Analysis
# -------------------------------------------------
print("-" * 65)
print("\nATTENDANCE ANALYSIS")
print("-" * 65)

low_attendance_students = df[df["attendance_percentage"] < 75]

if low_attendance_students.empty:

    print("All students have attendance above 75%")

else:

    for index, row in low_attendance_students.iterrows():

        print(f"Name                  : {row['name']}")
        print(f"Department            : {row['department']}")
        print(f"Attendance Percentage : {row['attendance_percentage']}%")
        print("-" * 40)

print("\nProject Completed Successfully")
print("=" * 65)

=================================================================
        STUDENT PERFORMANCE EXPLORER USING PANDAS
=================================================================
Datas are loaded
-----------------------------------------------------------------

FIRST 5 RECORDS
-----------------------------------------------------------------
   student_id          name  age  gender        department  semester  \
0        1001  Aarav Sharma   19    Male  Computer Science         2
1        1002   Priya Patel   20  Female  Computer Science         2
2        1003   Rohit Verma   19    Male       Electronics         2
3        1004   Sneha Reddy   20  Female        Mechanical         2
4        1005    Arjun Nair   19    Male  Computer Science         2

   math_score  science_score  english_score  programming_score  \
0          85             78             72                 91
1          76             82             88                 79
2          65             74             61                 55
3          70             80             75                 48
4          92             88             81                 95

   attendance_percentage       city  admission_year  total_score
0                     92     Mumbai            2023          176
1                     87  Ahmedabad            2023          155
2                     78      Delhi            2023          120
3                     95  Hyderabad            2023          118
4                     90      Kochi            2023          187
-----------------------------------------------------------------

DATASET OVERVIEW
-----------------------------------------------------------------
Total Number of Students : 30
Total Number of Columns  : 14
-----------------------------------------------------------------

DEPARTMENT-WISE ANALYSIS
-----------------------------------------------------------------
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64
-----------------------------------------------------------------

SCORE ANALYSIS
-----------------------------------------------------------------
Highest Math Score              : 95
Lowest Math Score               : 56
Average Math Score              : 76.07
Average Programming Score       : 67.60
Average Attendance Percentage   : 84.50%
-----------------------------------------------------------------

GENDER-WISE ANALYSIS
-----------------------------------------------------------------
Female Average Total Score : 148.67
Male Average Total Score : 138.67
-----------------------------------------------------------------

TOP 5 PERFORMERS
-----------------------------------------------------------------
Student Name : Ananya Das
Department   : Computer Science
Total Score  : 192
----------------------------------------
Student Name : Tanvi Mehta
Department   : Computer Science
Total Score  : 189
----------------------------------------
Student Name : Arjun Nair
Department   : Computer Science
Total Score  : 187
----------------------------------------
Student Name : Akanksha Yadav
Department   : Computer Science
Total Score  : 185
----------------------------------------
Student Name : Swati Kulkarni
Department   : Computer Science
Total Score  : 182
----------------------------------------
-----------------------------------------------------------------

ATTENDANCE ANALYSIS
-----------------------------------------------------------------
Name                  : Meera Joshi
Department            : Electronics
Attendance Percentage : 72%
----------------------------------------
Name                  : Rahul Mishra
Department            : Mechanical
Attendance Percentage : 68%
----------------------------------------
Name                  : Manoj Pandey
Department            : Civil
Attendance Percentage : 65%
----------------------------------------
Name                  : Harish Pillai
Department            : Electronics
Attendance Percentage : 74%
----------------------------------------
Name                  : Sanjay Dubey
Department            : Civil
Attendance Percentage : 70%
----------------------------------------
Name                  : Sunita Pillai
Department            : Civil
Attendance Percentage : 73%
----------------------------------------

Project Completed Successfully
=================================================================